# $Header: /users/source/archives/sccs_tools.vcs/certify/RCS/Makefile,v 1.1 1989/03/27 16:22:13 dickey Exp $
#
# $Log: Makefile,v $
# Revision 1.1  1989/03/27 16:22:13  dickey
# Initial revision
#
#	Revision 1.1  89/03/27  16:23:45  dickey
#	RCS_BASE
#	

####### (Development) ##########################################################
GET	= checkout

####### (Standard Lists) #######################################################
SOURCES	=\
	README\
	config_sheet.txt\
	release_notes.txt

####### (Standard Productions) #################################################
all:
clean:
clobber:
destroy:	; rm -f *
run_tests:
sources:	$(SOURCES)
install:
deinstall:

####### (Details of Productions) ###############################################
$(SOURCES):	; $(GET) $@
